# -*- coding: utf-8 -*-
"""atividade 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtDRKcfI2-PM9Iihta-EuvKNdQDUYYvi
"""

print('='*40)
 print("Verificando se o número é par ou ímpar")
 print('='*40)
 num = int(input('Digite um número inteiro: '))
 if num % 2 == 0:
     print(f"O número {num} é par")
 else:
     print(f"O número {num} é ímpar")