# -*- coding: utf-8 -*-
"""atividade 01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cjaSiX5yNDdOzsBgajGSqNfThTIO-lNF
"""

print("Calculadora de fatorial")
num = int(input("Digite um número para calcular o fatorial: "))
fatorial = 1
for i in range(1, num + 1):
      fatorial = fatorial * i
print("O fatorial de", num, "é", fatorial)