# -*- coding: utf-8 -*-
"""Atividade 15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UXzzmNBKjAEA3K3MJfEoZHRdrApAZBAu
"""

print("_" * 40)
print("Soma de números naturais")
print("_" * 40)

num = []
while True:
    n = int(input("Digite um número natural, ou digite -1 para ser feito o cálculo: "))
    if n == -1:
        break
    num.append(n)

soma = sum(num)
print(f"A soma dos números é {soma}")