# -*- coding: utf-8 -*-
"""atividade 02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/138BhKBI98fjJG2hueJCDWLbrFex7Sqhk
"""

print("Calculando esse calor da peste de Celsius para Fahrenheith")
celsius = float(input("Digite a temperatura em Celsius: "))
fahrenheit = (celsius * 9/5) + 32
print("A temperatura em Fahrenheit é:", fahrenheit)