# -*- coding: utf-8 -*-
"""atividade 17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/167ax8PItxyjU6-Yj_Fw-ObIysdAwAvgI
"""

print("=" * 60)
print("  Verificando se um número é ou não um número perfeito")
print("=" * 60)

num = int(input("Digite um número para saber se é ou não um número perfeito: "))

def num_perfeito(numero):
    if numero < 1:
        return False

    soma_divisores = 0
    for i in range(1, numero):
        if numero % i == 0:
            soma_divisores += i

    return soma_divisores == numero

if num_perfeito(num):
    print(f"O número {num} é perfeito.")
else:
    print(f"O número {num} não é perfeito.")