# -*- coding: utf-8 -*-
"""Atividade 13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UXzzmNBKjAEA3K3MJfEoZHRdrApAZBAu
"""

print("_"*40)
print("Soma de números pares de 1 a 100")
print("_"*40)
num = cont = 0 # Initialize cont to 0 for accurate sum
for num in range(1, 101):
  if num % 2 == 0: # Correct the modulo operation to check for even numbers
    cont += num
  print(num)
print(f'A soma dos numeros pares é: {cont}')