# -*- coding: utf-8 -*-
"""atividade 05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5SMZCqFKrL5l1If12i-_YeLm2aidD-V
"""

print("Tabuada de um número inteiro")
num = int(input("Digite um número inteiro :"))
for i in range(1,11):
    print(f"{num} x {i} = {num*i}")