# -*- coding: utf-8 -*-
"""Atividade 03ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uN_79osnZXGLKwngRyYRoy2QRJCgsbd4
"""

print("Calculadora de IMC")
peso = float(input("Digite seu peso em kilogramas:"))
altura = float(input("Digite sua altura em metros:"))
imc = peso / (altura * altura)
print("Seu Imc é :", imc)
if imc < 18.5:
    print("Tá passando fome em meu fi")
elif imc >= 18.5 and imc <= 24.9:
    print("Dentro dos padrões")
else:
    print("Uma academia iria bem")