# -*- coding: utf-8 -*-
"""Atividade 11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UXzzmNBKjAEA3K3MJfEoZHRdrApAZBAu
"""

print("_"*50)
print("Calculando a área de um círculo")
print("_"*50)
raio = float(input("Digite a medida do raio do círculo :"))
formula = raio * raio * 3.14
print(f"A área do círculo é {formula} .")