# -*- coding: utf-8 -*-
"""atividade 07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5SMZCqFKrL5l1If12i-_YeLm2aidD-V
"""

print("Calculadora de média")
nota = float(input("Digite os números para saber a média, ou digite -1 para finalizar : "))
num = 0
contador = 0

while nota != -1:
    contador += 1
    num += nota
    nota = float(input("Continue digitando os números: \n"))

media = num / contador
print("A média final é :", media)