# -*- coding: utf-8 -*-
"""Atividade 12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UXzzmNBKjAEA3K3MJfEoZHRdrApAZBAu
"""

print("_"*40)
print("++JOGO DE ADIVINHAÇÃO++")
print("-"*40)
import random
def jogo_adivinhacao():
    numero_secreto = random.randint(1, 100)
    tentativas = 0
    print("Bem-vindo ao jogo de adivinhação!")
    print("Tente adivinhar o número entre 1 e 100.")
    while True:
        try:
            palpite = int(input("Digite seu palpite: "))
            tentativas += 1
            if palpite < 1 or palpite > 100:
                print("Por favor, insira um número entre 1 e 100.")
                continue
            if palpite < numero_secreto:
                print("O número secreto é maior.")
            elif palpite > numero_secreto:
                print("O número secreto é menor.")
            else:
                print(f"Parabéns! Você acertou o número {numero_secreto} em {tentativas} tentativas.")
                break
        except ValueError:
            print("Entrada inválida. Por favor, insira um número inteiro.")
jogo_adivinhacao()