# -*- coding: utf-8 -*-
"""atividade 16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/167ax8PItxyjU6-Yj_Fw-ObIysdAwAvgI
"""

print("="*50)
print("Invertendo uma string")
print("="*50)
string = input("Digite uma palavra ou texto para ser invertido :")
string_invertida = string[::-1]
print(f"O texto ou palavra informado ficará assim :{string_invertida} , após ter sido invertido")