# -*- coding: utf-8 -*-
"""atividade 20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oc0hy-A97yhG2mbjTWXA9yaqBX3wdDe_
"""

print("_"*50)
print("Análise de lista de números")
print("_"*50)
lista = []
i = 0

while i != -1:
    num = int(input("Digite números inteiros, ou digite -1 para finalizar a lista: "))
    i = num
    if num != -1:
        lista.append(num)


menor = min(lista)
maior = max(lista)
soma = sum(lista)
quantidade = len(lista)

media = soma / quantidade

print(f"O menor número da lista é o {menor}, o maior é o {maior}. A média dos números digitados é {media}")