# -*- coding: utf-8 -*-
"""atividade 09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rKrmZKbK4FnNj9RxVcTJojeTjeQZU2_A
"""

print('-'*50)
print("Organizando 3 números inteiros em ordem crescente")
print('-'*50)
num1 = int(input("Digite o primeiro número: "))
num2 = int(input("Digite o segundo número: "))
num3 = int(input("Digite o terceiro número: "))
if num1 > num2:
    num1, num2 = num2, num1
if num1 > num3:
    num1, num3 = num3, num1
if num2 > num3:
    num2, num3 = num3, num2
print(f"A ordem crescente dos números é: {num1}, {num2} e {num3}")