# -*- coding: utf-8 -*-
"""atividade 04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5SMZCqFKrL5l1If12i-_YeLm2aidD-V
"""

print("Verificando se o texto é um políndromo")
def polindromo(string):
    if string == string[::-1]:
        print("É um políndromo")
        return True

    else:
        return False
        return False

texto = input("Digite o texto: ")
print(polindromo(texto))