# -*- coding: utf-8 -*-
"""Atividade 18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UXzzmNBKjAEA3K3MJfEoZHRdrApAZBAu
"""

print("=" * 60)
print("              Contagem de palavras de uma frase")
print("=" * 60)

frase = input("Digite uma frase:")
palavras = frase.split()
contagem = len(palavras)
print("A frase tem {} palavras".format(contagem))