# -*- coding: utf-8 -*-
"""atividade3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_C2o1ND1VfbrcgE0AQU5jf7DfFLS_s-N
"""

num1 = int(input("Digite o primeiro número : "))
num2 = int(input("Digite o segundo número : "))

soma = num1+num2
sub = num1 - num2
prod = num1 * num2
div = num1 / num2

print("Soma entre {} e {} é igual a {}".format(num1, num2, soma))
print("Subtração entre {} e {} é igual a {}" .format(num1, num2, sub))
print("Multiplicação entre {} e {} é igual a {}" .format(num1, num2, prod))
print("Divisão entre {} e {} é igual a {}" .format(num1, num2, div))