# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvD_scJcplqLlWXKuza4s4mnGaxUUvJY
"""

contador = 1
for i in range(10):
    contador= i+1
    if contador%2==0:
        print(contador)