# -*- coding: utf-8 -*-
"""atividade4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CQRA5LXsjtc8mI8G29whkhL0wgEynpz2
"""

temp = float(input("Qual é a temperatura atual ? "))
if temp <= 15:
 print("Friozinho gostoso, tome cuidado para não congelar.")
elif temp >=15.1 and temp <=29.9:
 print("Eita que climinha agradável")
else:
 print("Eita calor da mulestia.")