# -*- coding: utf-8 -*-
"""Atividade 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrpr5TEpH7BPLad4SQQ8CSNNwDhus2X0
"""

usuario = input("Digite seu nome de usuário: ")
filme = input("Qual é o nome do seu filme favorito ?: ")
anolancamento = input("Em que ano lançou esse filme ?: ")

print("O filme favorito do usuário " +usuario+ " é " +filme+ ", lançado em " +anolancamento+".")