# -*- coding: utf-8 -*-
"""Atividade 09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ctf8xEy4sjPSgvnwp9ByMTMlFgdmvzxm
"""

texto = input("Digite um texto :")
letra = input("Digite uma letra para ser contada :")
texto.count(letra)
print(f"A letra {letra} aparece {texto.count(letra)} vezes no texto digitado")