# -*- coding: utf-8 -*-
"""atividade 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HwbKhEnXRIVeP9AZMQLpzin9-ylN_LXc
"""

lista = []
while True:

    item = input("Digite um item para adicionar à lista (ou 'sair' para encerrar): ")

    if item.lower() == 'sair':
        break

    lista.append(item)

    print(f"Item '{item}' adicionado à lista.")
print("Lista :")
for item in lista:
    print("+", item)