# -*- coding: utf-8 -*-
"""atividade6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvD_scJcplqLlWXKuza4s4mnGaxUUvJY
"""

num = int(input("Digite um valor inteiro para soma ou 0 para encerrá-la \n"))
i=0
soma=0

while(i<=num):
  cont =int(input())
  soma = soma + cont
  i = i+1
  if(cont == 0):
    print("A soma dos valores é igual a {}" .format(soma))